spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    url: jdbc:h2:mem:testdb
    user: ${H2_USERNAME}
    password: ${H2_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true